@ECHO OFF
@ECHO Get All Boxer Software Macros ...
for /r "c:\users\any2c\documents\boxer text editor" %%f in (WSH*.bm) do copy /y "%%f" c:\users\any2c\documents\github\d2e\progs\boxer > nul 2>&1 
@ECHO Get All D2e Config Files ...
for /r "c:\users\any2c\documents\origfls\software vault\games\descent second edition\assets" %%f in (*config*.txt) do copy /y "%%f" c:\users\any2c\documents\github\d2e\progs\config > nul 2>&1
@ECHO Get All D2e Data Files ...
for /r "c:\users\any2c\documents\origfls\software vault\games\descent second edition\assets" %%f in (*data*.txt) do copy /y "%%f" c:\users\any2c\documents\github\d2e\progs\data > nul 2>&1
PAUSE
